---
kind: pipeline
type: docker
name: node-sample-app

trigger:
  branch:
    - main
  event:
    - push

steps:
- name: backend
  image: node:16-alpine
  commands:
  - npm install
  - npm test

---

kind: pipeline
type: ssh
name: windows-ssh

platform:
  os: windows

server:
  host:
    from_secret: windows_host
  password:
    from_secret: windows_password
  user:
    from_secret: windows_username

steps:
- name: build_latest
  environment:
    HOSTNAME:
      from_secret: windows_host
    # VERSION: 21H2
    # USERNAME:
    #   from_secret: docker_username
    # PASSWORD:
    #   from_secret: docker_password
  commands:
  - powershell.exe scripts/windows/latest.ps1
  when:
    event: [ push ]

# - name: build_tag
#   environment:
#     VERSION: 21H2
#     USERNAME:
#       from_secret: docker_username
#     PASSWORD:
#       from_secret: docker_password
#   commands:
#   - powershell.exe scripts/windows/tag.ps1
#   when:
#     event: [ tag ]

depends_on:
- node-sample-app

trigger:
  ref:
  - refs/heads/main
  - refs/tags/*
